const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=process.argv[2];
function source(n){return fs.readFileSync(root+'/src/'+n,'utf8').trim().split('\n').map(JSON.parse).join('');}
let id=0;function el(){return {nodeType:1,tagName:'DIV',id:'n'+id++,className:'',attributes:[],firstChild:null,parentElement:null,isConnected:true,scrollTop:0,scrollLeft:0,scrollHeight:100,scrollWidth:430,clientHeight:100,clientWidth:430,hasAttribute:()=>false,getAttribute:()=>'',getBoundingClientRect:()=>({x:0,y:0,top:0,left:0,right:430,bottom:100,width:430,height:100}),scrollTo(p){this.scrollTop=Math.max(0,Math.min(p.top,this.scrollHeight-this.clientHeight));this.scrollLeft=p.left;}};}
let elements=Array.from({length:400},el),html=elements[0],inner=elements[10];html.scrollHeight=5000;html.clientHeight=800;html.scrollTop=122;inner.scrollHeight=2400;inner.clientHeight=500;inner.scrollTop=77;elements.forEach(e=>Object.defineProperty(e,'textContent',{get(){throw Error('subtree text read');}}));
let tasks=[],messages=[],listener;
const context={document:{documentElement:html,scrollingElement:html,body:html,readyState:'complete',referrer:'',getElementsByTagName:()=>elements,querySelectorAll:()=>[],querySelector:()=>null,elementsFromPoint:()=>[],createTreeWalker(){let i=0;return {nextNode:()=>elements[++i]||null};}},location:{pathname:'/dp/x',origin:'https://example.test'},getComputedStyle(e){return {display:'block',visibility:'visible',opacity:'1',overflowY:e===inner?'auto':'visible',overflowX:'visible',backgroundColor:'rgb(0, 0, 0)',color:'rgb(255, 255, 255)'};},performance:{timeOrigin:1},setTimeout(f){tasks.push(f);},console};
context.window=context;context.innerWidth=430;context.innerHeight=800;context.addEventListener=(name,f)=>{listener=f;};context.webkit={messageHandlers:{adUniversalUI7433:{postMessage:m=>messages.push(m)}}};vm.createContext(context);
context.__adUIProbeMode7362='full';context.__adUIProbePhase7364='final-full';
let result=JSON.parse(vm.runInContext(source('ADUniversalUIProbe7362.js.inc'),context)),count=0,batches=0;
while(true){assert(!result.error,result.error);assert(result.nodes.length<=32);count+=result.nodes.length;batches++;if(!result.more)break;result=JSON.parse(context.__adUIProbeContinue7446());assert(batches<100);}
assert.equal(count,400);assert(batches>=4);assert(context.__adUIProbeScrollOwners7449.includes(inner));
const nav=source('ADUIProbeScroll7446.js.inc');function command(x){context.__adUIWalkCommand7449=x;return vm.runInContext(nav,context);}
assert.equal(command('initroot').y,0);assert.equal(command(2000).y,2000);html.scrollHeight=6200;assert.equal(command('read').max,5400);assert(command('next').done);assert.equal(html.scrollTop,2000,'next must not flash back to top');assert.equal(command('initowners').index,0);assert.equal(command(1900).y,1900);assert(command('next').done);command('restore');assert.equal(inner.scrollTop,77);assert.equal(html.scrollTop,122);
vm.runInContext(source('ADUniversalUIProbe7362.frame.js.inc'),context);listener({data:{__adUIProbe7433:1,nonce:'n',captureId:'c',mode:'full',phase:'final-full',step:0,depth:1}});let spins=0;while(tasks.length){tasks.shift()();assert(++spins<100);}
let grouped={};messages.forEach(m=>{(grouped[m.captureId] ||= [])[m.seq]=m.payload;});let payloads=Object.values(grouped).map(chunks=>JSON.parse(chunks.join('')));assert.equal(payloads.reduce((n,p)=>n+p.nodes.length,0),400);assert(payloads.length>=4);assert(payloads.every(p=>p.nodes.length<=48));console.log('PASS: cooperative final-full collector yields 400-node fixture; root/owner offsets restore independently');
