#import "ADSponsored.h"

// v7.387: adjacent simple selector rules share an identical collapse declaration.
// Comma lists preserve each selector's specificity. Every :has() remains isolated,
// in the original order, so an unsupported relational selector cannot reject its peers.
// No selector is broadened, dropped, or reconstructed in the WebContent process.
NSString *ADKillerSponsoredJS7384(void){
    return
    @"(function(){try{var d=document;if(d.getElementById('ad7384-killer'))return;var s=d.createElement('style');s.id='ad7384-killer';s.textContent=\"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[data-csa-c-painter=\\\"gwm-asin-tile\\\"][class*=\\\"mobile-gateway-atf_Spons\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"li[class*=\\\"_hp-mosaic-container_style_widgetContainer_\\\"]:has(>div[data-csa-c-painter=\\\"npack-asin-card-cards\\\"]>div[id^=\\\"CardInstance\\\"]>.a-cardui>.a-cardui-header [class*=\\\"_widget-sponsored-badge-container_\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[data-ad-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[data-cel-widget^=\\\"mobile-ads-\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[cel_widget_id^=\\\"adplacements:\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[class*=\\\"mobile-gateway-atf_ad-\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[data-csa-c-painter=\\\"single-creative-card\\\"] [data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#gwm-dashboard>li.gwm-tile:has(>span.a-list-item>div[data-csa-c-painter=\\\"single-video-card\\\"] [data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".a-cardui[class*=\\\"_new-detail-faceout-box_\\\"]:has(.dynamicSponsoredLabelClass){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".a-carousel-card:has(.p13n-sc-sponsored-label){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".amzn-safe-frame-container,.ape-wrapper{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".dp-widget-card-deck:has([data-ad-placement-metadata]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-item.AdHolder{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-item:has([data-ad-feedback]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-item:has([data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-list > .a-section:has(.sbv-ad-content-container){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".p13n-sc-unified-ad-label,.sbv-video-single-product,.sponsored-products-detail-mobile,#detailILM_feature_div{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#faceoutContainer:has(> [class$=\\\"sponsored-label\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#mobile-mshop-ad,#nav-swmslot,#sc-rec-bottom,#sc-rec-right{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#similarities_feature_div:has(span.sponsored_label_tap_space){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"#sponsoredProducts2_feature_div,#sponsoredProducts_feature_div,#sponsored-proofPoint-section,#typ-recommendations-stripe-1,#typ-recommendations-stripe-2,[cel_widget_id*=\\\"-creative-desktop_loom-desktop-\\\"],[data-ad-id],[data-component-type^=\\\"aspa-asin-ajax\\\"],[id^=\\\"ape_\\\"],[id^=\\\"mobile-dp-ilm\\\"]{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div.s-inner-result-item > div.sg-col-inner:has(a.puis-sponsored-label-text){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-item:has(.puis-sponsored-label-text){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[cel_widget_id*=\\\"_ad-placements-\\\"],div[cel_widget_id*=\\\"Deals3Ads\\\"],[class*=\\\"_adFeedbackWrapper_\\\"],div[cel_widget_id*=\\\"desktop-dp-\\\"],div[cel_widget_id=\\\"sp-orderdetails-desktop-carousel_desktop-yo-orderdetails_0\\\"],div[cel_widget_id=\\\"sp-orderdetails-mobile-list_mobile-yo-orderdetails_0\\\"],div[cel_widget_id=\\\"sp-pop-mobile-carousel_mobile-yo-postdelivery_0\\\"],div[cel_widget_id=\\\"sp-rhf-desktop-carousel_desktop-rhf_0\\\"],div[cel_widget_id=\\\"sp-shiptrack-desktop-carousel_desktop-yo-shiptrack_0\\\"],div[cel_widget_id=\\\"sp-shiptrack-mobile-list_mobile-yo-shiptrack_0\\\"],div[cel_widget_id=\\\"sp-typ-mobile-carousel_mobile-typ-carousels_2\\\"],div[cel_widget_id=\\\"sp_phone_detail_thematic\\\"],div[cel_widget_id=\\\"typ-ads\\\"],div[cel_widget_id^=\\\"LEFT-SAFE_FRAME-\\\"]{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @".s-result-item:has(div[cel_widget_id^=\\\"MAIN-FEATURED_ASINS_LIST-\\\"]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[cel_widget_id^=\\\"MAIN-FEATURED_ASINS_LIST-\\\"],div[cel_widget_id^=\\\"MAIN-VIDEO_SINGLE_PRODUCT-\\\"],div[cel_widget_id^=\\\"adplacements:\\\"],div[cel_widget_id^=\\\"multi-brand-\\\"],div[cel_widget_id^=\\\"sb-\\\"],div[cel_widget_id^=\\\"sp-desktop-carousel_handsfree-browse\\\"],div[cel_widget_id^=\\\"sp-mobile-thematic-bundle\\\"],div[class*=\\\"SponsoredProducts\\\"],div[class*=\\\"_dpNoOverflow_\\\"][data-idt],div[data-a-carousel-options*='\\\"isSponsoredProduct\\\":\\\"true\\\"'],div[data-cel-widget=\\\"sp-rhf-desktop-carousel_desktop-rhf_1\\\"],div[data-cel-widget=\\\"sp-shiptrack-desktop-carousel_desktop-yo-shiptrack_0\\\"],div[data-cel-widget^=\\\"mobile-ads-\\\"],div[data-cel-widget^=\\\"multi-brand-video-mobile_DPSims_\\\"],div[data-cel-widget^=\\\"multi-brand-video-mobile_DetailPage_\\\"],div[data-cel-widget^=\\\"multi-card-creative-desktop_loom-desktop-top-slot_\\\"],div[data-cel-widget^=\\\"sb-\\\"],div[data-cel-widget^=\\\"sp-mobile-thematic-bundle\\\"],div[cel_widget_id^=\\\"sb-themed-collection\\\"],div[data-cel-widget*=\\\"-mobile_loom-mobile-inline-slot\\\"]{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[data-csa-c-painter=\\\"single-creative-card\\\"]:has([data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[data-csa-c-painter=\\\"single-video-card\\\"]:has([data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"li.gwm-window-tile:has(div[data-csa-c-painter=\\\"single-creative-card\\\"] [data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"li.gwm-window-tile:has(div[data-csa-c-painter=\\\"single-video-card\\\"] [data-ad-feedback-label-id]){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[data-csa-c-painter=\\\"sp-cart-mobile-carousel-cards\\\"],div[data-csa-c-slot-id^=\\\"loom-mobile-brand-footer-slot_hsa-id-\\\"],div[data-csa-c-slot-id^=\\\"loom-mobile-top-slot_hsa-id-\\\"]{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[id^=\\\"sims-simsContainer_feature_div_\\\"]:has(.sp_info_link){display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\\n"
    @"div[id^=\\\"sp_detail\\\"],span[cel_widget_id^=\\\"MAIN-FEATURED_ASINS_LIST-\\\"],span[cel_widget_id^=\\\"MAIN-loom-desktop-brand-footer-slot_hsa-id-CARDS-\\\"],span[cel_widget_id^=\\\"MAIN-loom-desktop-top-slot_hsa-id-CARDS-\\\"]{display:none!important;width:0!important;min-width:0!important;max-width:0!important;height:0!important;min-height:0!important;max-height:0!important;flex:0 0 0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;}\";(d.head||d.documentElement).appendChild(s)}catch(_){}})();";
}
